#ifndef WASTETEMPLATES_H
#define WASTETEMPLATES_H

struct WasteTemplateData {
  const char* shape;           
  const char* dominantColor;   
  float colorVariance;         
  const char* texture;         
  const char* branding;        
  int edgeDensity;             
  bool heatPacking;            
  bool metalDetected;          
  bool attachmentDetected;     
};

struct WasteTemplate {
  int id;
  const char* name;
  const char* description;
  const char* category;        
  WasteTemplateData data;
};

WasteTemplate wasteTemplates[] = {
  {  0, "Plastic Bottle", "Transparent plastic bottle used for beverages", "Recyclable", {"cylindrical", "clear", 0.12, "smooth", "Coke", 10, false, false, false} },
  {  1, "Green Bottle", "Green colored glass bottle used for beverages", "Recyclable", {"cylindrical", "green", 0.10, "smooth", "Pepsi", 12, false, true, false} },
  {  2, "Aluminum Can", "Aluminum beverage can", "Recyclable", {"cylindrical", "silver", 0.08, "smooth", "Coke", 15, false, true, false} },
  {  3, "Paper Cup", "Disposable paper cup", "Biodegradable", {"conical", "white", 0.20, "rough", "Generic", 18, true, false, false} },
  {  4, "Plastic Cup", "Disposable plastic cup", "Non-Biodegradable", {"conical", "blue", 0.15, "smooth", "Generic", 14, false, false, false} },
  {  5, "Plastic Fork", "Disposable plastic fork", "Non-Biodegradable", {"irregular", "white", 0.30, "patterned", "None", 25, false, false, true} },
  {  6, "Plastic Knife", "Disposable plastic knife", "Non-Biodegradable", {"irregular", "white", 0.28, "patterned", "None", 24, false, false, true} },
  {  7, "Paper Plate", "Disposable paper plate", "Biodegradable", {"circular", "white", 0.22, "rough", "EcoPack", 20, true, false, false} },
  {  8, "Plastic Plate", "Disposable plastic plate", "Non-Biodegradable", {"circular", "white", 0.18, "smooth", "Generic", 16, false, false, false} },
  {  9, "Canned Food", "Metal can containing food", "Non-Biodegradable", {"rectangular", "silver", 0.10, "smooth", "FoodCo", 13, false, true, false} },
  { 10, "Sandwich Wrapper", "Foil and plastic laminated wrapper", "Non-Biodegradable", {"irregular", "multicolor", 0.35, "rough", "None", 30, true, true, true} },
  { 11, "Fruit Container", "Plastic container for cut fruit", "Recyclable", {"rectangular", "transparent", 0.14, "smooth", "FreshPack", 11, false, false, false} },
  { 12, "Yogurt Container", "Small plastic container for yogurt", "Recyclable", {"rectangular", "white", 0.16, "smooth", "Yum", 12, false, false, false} },
  { 13, "Ice Cream Cup", "Paper cup for ice cream", "Biodegradable", {"circular", "white", 0.25, "rough", "CoolTreat", 19, true, false, false} },
  { 14, "Plastic Straw", "Disposable plastic straw", "Non-Biodegradable", {"cylindrical", "transparent", 0.05, "smooth", "None", 5, false, false, false} },
  { 15, "Paper Bag", "Paper bag for food packaging", "Biodegradable", {"rectangular", "brown", 0.30, "rough", "EcoPack", 22, true, false, false} },
  { 16, "Plastic Bag", "Disposable plastic bag", "Non-Biodegradable", {"irregular", "transparent", 0.20, "smooth", "None", 17, false, false, false} },
  { 17, "Napkin", "Paper napkin", "Biodegradable", {"irregular", "white", 0.40, "rough", "None", 28, true, false, false} },
  { 18, "Food Tray", "Disposable foam tray", "Non-Biodegradable", {"rectangular", "white", 0.12, "smooth", "FoamCo", 14, false, false, true} },
  { 19, "Plastic Lid", "Plastic lid for cups", "Non-Biodegradable", {"circular", "white", 0.10, "smooth", "Generic", 9, false, false, false} },
  { 20, "Glass Jar", "Glass jar for sauces or spreads", "Recyclable", {"cylindrical", "clear", 0.09, "smooth", "Generic", 13, false, true, false} },
  { 21, "Metal Spoon", "Disposable metal spoon", "Recyclable", {"irregular", "silver", 0.07, "smooth", "FoodCo", 10, false, true, false} },
  { 22, "Plastic Spoon", "Disposable plastic spoon", "Non-Biodegradable", {"irregular", "white", 0.28, "smooth", "None", 23, false, false, true} },
  { 23, "Disposable Bowl", "Paper or plastic bowl", "Biodegradable", {"circular", "white", 0.18, "rough", "EcoPack", 17, true, false, false} },
  { 24, "Condiment Packet", "Small packet for sauces", "Non-Biodegradable", {"rectangular", "multicolor", 0.32, "patterned", "FoodCo", 26, true, false, false} },
  { 25, "Salad Container", "Plastic container for salads", "Recyclable", {"rectangular", "transparent", 0.15, "smooth", "FreshPack", 12, false, false, false} },
  { 26, "Sandwich Box", "Cardboard box for sandwiches", "Biodegradable", {"rectangular", "brown", 0.20, "rough", "EcoPack", 18, true, false, false} },
  { 27, "Cardboard Packaging", "Corrugated cardboard packaging", "Biodegradable", {"rectangular", "brown", 0.35, "rough", "None", 27, true, false, false} },
  { 28, "Snack Wrapper", "Plastic wrapper for snacks", "Non-Biodegradable", {"irregular", "multicolor", 0.38, "patterned", "SnackCo", 29, true, false, false} },
  { 29, "Juice Carton", "Composite carton for juice", "Recyclable", {"rectangular", "orange", 0.22, "smooth", "Juicy", 16, true, false, false} },
  { 30, "Milk Carton", "Paper-based carton for milk", "Biodegradable", {"rectangular", "white", 0.25, "rough", "DairyBest", 18, true, false, false} },
  { 31, "Beverage Can", "Metal can for soft drinks", "Recyclable", {"cylindrical", "silver", 0.10, "smooth", "SodaPop", 15, false, true, false} },
  { 32, "Hot Dog Wrapper", "Paper wrapper for hot dogs", "Biodegradable", {"irregular", "red", 0.33, "rough", "StreetEats", 27, true, false, false} },
  { 33, "Ice Cream Cone", "Paper cone for ice cream", "Biodegradable", {"conical", "brown", 0.30, "rough", "CoolTreat", 20, true, false, false} },
  { 34, "Plastic Cutlery Set", "Set of disposable plastic utensils", "Non-Biodegradable", {"irregular", "white", 0.35, "patterned", "None", 30, false, false, true} },
  { 35, "Recyclable Paper Bag", "Paper bag with recycling symbol", "Biodegradable", {"rectangular", "brown", 0.28, "rough", "EcoPack", 23, true, false, false} },
  { 36, "Coffee Cup Sleeve", "Paper sleeve for coffee cups", "Biodegradable", {"cylindrical", "brown", 0.20, "rough", "CoffeeCo", 14, true, false, false} },
  { 37, "Small Plastic Container", "Mini plastic container for condiments", "Recyclable", {"rectangular", "transparent", 0.17, "smooth", "CondCo", 11, false, false, false} },
  { 38, "Food Packaging Film", "Thin plastic film for wrapping food", "Non-Biodegradable", {"irregular", "transparent", 0.12, "smooth", "None", 8, false, false, false} },
  { 39, "Disposable Straw Pack", "Pack of multiple plastic straws", "Non-Biodegradable", {"cylindrical", "transparent", 0.05, "smooth", "None", 6, false, false, false} },
  { 40, "Chocolate Wrapper", "Foil wrapper for chocolate bars", "Non-Biodegradable", {"irregular", "multicolor", 0.40, "patterned", "Choco", 32, true, true, false} },
  { 41, "Granola Bar Wrapper", "Plastic/foil wrapper for granola bars", "Non-Biodegradable", {"irregular", "multicolor", 0.38, "patterned", "GranolaCo", 31, true, true, false} },
  { 42, "Fruit Peel", "Organic peel from fruits", "Biodegradable", {"irregular", "orange", 0.45, "rough", "None", 35, true, false, false} },
  { 43, "Vegetable Peel", "Organic peel from vegetables", "Biodegradable", {"irregular", "green", 0.47, "rough", "None", 36, true, false, false} },
  { 44, "Paper Napkin", "Thin paper napkin", "Biodegradable", {"irregular", "white", 0.42, "rough", "None", 34, true, false, false} },
  { 45, "Plastic Utensil Pack", "Pack of assorted plastic utensils", "Non-Biodegradable", {"irregular", "white", 0.36, "patterned", "None", 29, false, false, true} },
  { 46, "Paper Lid", "Paper lid for disposable cups", "Biodegradable", {"circular", "white", 0.20, "rough", "EcoPack", 15, true, false, false} },
  { 47, "Plastic Lid 2", "Alternative design plastic cup lid", "Non-Biodegradable", {"circular", "white", 0.18, "smooth", "Generic", 12, false, false, false} },
  { 48, "Plastic Tray", "Disposable plastic food tray", "Non-Biodegradable", {"rectangular", "white", 0.22, "smooth", "FoodCo", 19, false, false, true} },
  { 49, "Reusable Water Bottle", "Durable reusable plastic bottle", "Recyclable", {"cylindrical", "blue", 0.10, "smooth", "EcoPack", 10, false, false, false} },
  { 50, "Paper Straw", "Thin paper straw", "Biodegradable", {"cylindrical", "white", 0.15, "smooth", "None", 8, true, false, false} },
  { 51, "Plastic Stirrer", "Disposable plastic stirrer", "Non-Biodegradable", {"irregular", "white", 0.20, "smooth", "None", 7, false, false, false} },
  { 52, "Milk Carton (Small)", "Small plastic milk carton", "Biodegradable", {"rectangular", "white", 0.18, "rough", "DairyBest", 13, true, false, false} },
  { 53, "Fruit Cup", "Disposable fruit cup", "Recyclable", {"rectangular", "transparent", 0.16, "smooth", "FreshPack", 11, false, false, false} },
  { 54, "Juice Bottle", "Plastic bottle for juice", "Recyclable", {"cylindrical", "orange", 0.14, "smooth", "Juicy", 10, false, false, false} },
  { 55, "Soda Bottle", "Clear soda bottle", "Recyclable", {"cylindrical", "clear", 0.12, "smooth", "Coke", 10, false, false, false} },
  { 56, "Water Cup", "Paper water cup", "Biodegradable", {"conical", "white", 0.22, "rough", "Generic", 16, true, false, false} },
  { 57, "Snack Box", "Small cardboard snack box", "Biodegradable", {"rectangular", "brown", 0.30, "rough", "EcoPack", 20, true, false, false} },
  { 58, "Candy Wrapper", "Foil wrapper for candy", "Non-Biodegradable", {"irregular", "multicolor", 0.38, "patterned", "CandyCo", 28, true, false, false} },
  { 59, "Cookie Bag", "Plastic bag for cookies", "Non-Biodegradable", {"irregular", "transparent", 0.20, "smooth", "None", 17, false, false, false} },
  { 60, "Sandwich Wrap", "Paper sandwich wrap", "Biodegradable", {"irregular", "white", 0.35, "rough", "None", 30, true, false, false} },
  { 61, "Salad Cup", "Clear plastic salad cup", "Recyclable", {"rectangular", "transparent", 0.17, "smooth", "FreshPack", 11, false, false, false} },
  { 62, "Cutlery Set", "Disposable cutlery set", "Non-Biodegradable", {"irregular", "white", 0.33, "patterned", "None", 27, false, false, true} },
  { 63, "Plastic Knife 2", "Another disposable plastic knife", "Non-Biodegradable", {"irregular", "white", 0.29, "patterned", "None", 24, false, false, true} },
  { 64, "Plastic Fork 2", "Another disposable plastic fork", "Non-Biodegradable", {"irregular", "white", 0.31, "patterned", "None", 26, false, false, true} },
  { 65, "Paper Plate Small", "Small disposable paper plate", "Biodegradable", {"circular", "white", 0.23, "rough", "EcoPack", 18, true, false, false} },
  { 66, "Plastic Plate Small", "Small disposable plastic plate", "Non-Biodegradable", {"circular", "white", 0.19, "smooth", "Generic", 16, false, false, false} },
  { 67, "Cardboard Box Small", "Small cardboard food box", "Biodegradable", {"rectangular", "brown", 0.32, "rough", "EcoPack", 21, true, false, false} },
  { 68, "Plastic Container Small", "Small plastic container", "Recyclable", {"rectangular", "transparent", 0.16, "smooth", "CondCo", 12, false, false, false} },
  { 69, "Glass Bottle Small", "Small glass bottle", "Recyclable", {"cylindrical", "clear", 0.11, "smooth", "Generic", 13, false, true, false} },
  { 70, "Metal Can Small", "Small metal can", "Recyclable", {"cylindrical", "silver", 0.09, "smooth", "FoodCo", 14, false, true, false} },
  { 71, "Paper Napkin 2", "Another paper napkin", "Biodegradable", {"irregular", "white", 0.43, "rough", "None", 35, true, false, false} },
  { 72, "Paper Towel", "Disposable paper towel", "Biodegradable", {"irregular", "white", 0.44, "rough", "None", 36, true, false, false} },
  { 73, "Coffee Cup Lid", "Lid for disposable coffee cup", "Non-Biodegradable", {"circular", "white", 0.11, "smooth", "Generic", 9, false, false, false} },
  { 74, "Straw Pack", "Pack of paper straws", "Biodegradable", {"cylindrical", "white", 0.15, "smooth", "None", 8, true, false, false} },
  { 75, "Snack Wrapper 2", "Another snack wrapper", "Non-Biodegradable", {"irregular", "multicolor", 0.39, "patterned", "SnackCo", 29, true, false, false} },
  { 76, "Plastic Bag 2", "Another plastic bag", "Non-Biodegradable", {"irregular", "transparent", 0.21, "smooth", "None", 17, false, false, false} },
  { 77, "Paper Bag 2", "Another paper bag", "Biodegradable", {"rectangular", "brown", 0.29, "rough", "EcoPack", 22, true, false, false} },
  { 78, "Plastic Cup 2", "Another plastic cup", "Non-Biodegradable", {"conical", "blue", 0.16, "smooth", "Generic", 14, false, false, false} },
  { 79, "Aluminum Tray", "Aluminum food tray", "Recyclable", {"rectangular", "silver", 0.10, "smooth", "FoodCo", 15, false, true, false} },
  { 80, "Foam Cup", "Disposable foam cup", "Non-Biodegradable", {"conical", "white", 0.24, "rough", "Generic", 17, false, false, false} },
  { 81, "Plastic Bottle 2", "Another plastic bottle", "Recyclable", {"cylindrical", "clear", 0.12, "smooth", "Coke", 10, false, false, false} },
  { 82, "Glass Jar 2", "Another glass jar", "Recyclable", {"cylindrical", "clear", 0.10, "smooth", "Generic", 13, false, true, false} },
  { 83, "Metal Spoon 2", "Another metal spoon", "Recyclable", {"irregular", "silver", 0.08, "smooth", "FoodCo", 10, false, true, false} },
  { 84, "Plastic Spoon 2", "Another plastic spoon", "Non-Biodegradable", {"irregular", "white", 0.28, "smooth", "None", 23, false, false, true} },
  { 85, "Disposable Bowl 2", "Another disposable bowl", "Biodegradable", {"circular", "white", 0.18, "rough", "EcoPack", 17, true, false, false} },
  { 86, "Condiment Packet 2", "Another condiment packet", "Non-Biodegradable", {"rectangular", "multicolor", 0.32, "patterned", "FoodCo", 26, true, false, false} },
  { 87, "Salad Container 2", "Another plastic salad container", "Recyclable", {"rectangular", "transparent", 0.15, "smooth", "FreshPack", 12, false, false, false} },
  { 88, "Sandwich Box 2", "Another cardboard sandwich box", "Biodegradable", {"rectangular", "brown", 0.20, "rough", "EcoPack", 18, true, false, false} },
  { 89, "Cardboard Packaging 2", "Another cardboard packaging", "Biodegradable", {"rectangular", "brown", 0.35, "rough", "None", 27, true, false, false} },
  { 90, "Snack Wrapper 3", "Yet another snack wrapper", "Non-Biodegradable", {"irregular", "multicolor", 0.38, "patterned", "SnackCo", 29, true, false, false} },
  { 91, "Juice Carton 2", "Another juice carton", "Recyclable", {"rectangular", "orange", 0.22, "smooth", "Juicy", 16, true, false, false} },
  { 92, "Milk Carton 2", "Another milk carton", "Biodegradable", {"rectangular", "white", 0.25, "rough", "DairyBest", 18, true, false, false} },
  { 93, "Beverage Can 2", "Another beverage can", "Recyclable", {"cylindrical", "silver", 0.10, "smooth", "SodaPop", 15, false, true, false} },
  { 94, "Hot Dog Wrapper 2", "Another hot dog wrapper", "Biodegradable", {"irregular", "red", 0.33, "rough", "StreetEats", 27, true, false, false} },
  { 95, "Ice Cream Cone 2", "Another ice cream cone", "Biodegradable", {"conical", "brown", 0.30, "rough", "CoolTreat", 20, true, false, false} },
  { 96, "Plastic Cutlery Set 2", "Another plastic cutlery set", "Non-Biodegradable", {"irregular", "white", 0.35, "patterned", "None", 30, false, false, true} },
  { 97, "Recyclable Paper Bag 2", "Another recyclable paper bag", "Biodegradable", {"rectangular", "brown", 0.28, "rough", "EcoPack", 23, true, false, false} },
  { 98, "Coffee Cup Sleeve 2", "Another coffee cup sleeve", "Biodegradable", {"cylindrical", "brown", 0.20, "rough", "CoffeeCo", 14, true, false, false} },
  { 99, "Small Plastic Container 2", "Another small plastic container", "Recyclable", {"rectangular", "transparent", 0.17, "smooth", "CondCo", 11, false, false, false} },
  { 100, "Food Packaging Film 2", "Another food packaging film", "Non-Biodegradable", {"irregular", "transparent", 0.12, "smooth", "None", 8, false, false, false} },
  { 101, "Disposable Straw Pack 2", "Another pack of disposable straws", "Non-Biodegradable", {"cylindrical", "transparent", 0.05, "smooth", "None", 6, false, false, false} },
  { 102, "Chocolate Wrapper 2", "Another chocolate wrapper", "Non-Biodegradable", {"irregular", "multicolor", 0.40, "patterned", "Choco", 32, true, true, false} },
  { 103, "Granola Bar Wrapper 2", "Another granola bar wrapper", "Non-Biodegradable", {"irregular", "multicolor", 0.38, "patterned", "GranolaCo", 31, true, true, false} },
  { 104, "Fruit Peel 2", "Another fruit peel", "Biodegradable", {"irregular", "orange", 0.45, "rough", "None", 35, true, false, false} },
  { 105, "Vegetable Peel 2", "Another vegetable peel", "Biodegradable", {"irregular", "green", 0.47, "rough", "None", 36, true, false, false} },
  { 106, "Paper Napkin 3", "Yet another paper napkin", "Biodegradable", {"irregular", "white", 0.42, "rough", "None", 34, true, false, false} },
  { 107, "Plastic Utensil Pack 2", "Another pack of plastic utensils", "Non-Biodegradable", {"irregular", "white", 0.36, "patterned", "None", 29, false, false, true} },
  { 108, "Paper Lid 2", "Another paper lid", "Biodegradable", {"circular", "white", 0.20, "rough", "EcoPack", 15, true, false, false} },
  { 109, "Plastic Lid 3", "Yet another plastic lid", "Non-Biodegradable", {"circular", "white", 0.18, "smooth", "Generic", 12, false, false, false} },
  { 110, "Plastic Tray 2", "Another disposable plastic tray", "Non-Biodegradable", {"rectangular", "white", 0.22, "smooth", "FoodCo", 19, false, false, true} },
  { 111, "Reusable Water Bottle 2", "Another durable reusable bottle", "Recyclable", {"cylindrical", "blue", 0.10, "smooth", "EcoPack", 10, false, false, false} },
  { 112, "Cereal Box", "Cardboard cereal packaging", "Biodegradable", {"rectangular", "brown", 0.33, "rough", "Generic", 24, true, false, false} },
  { 113, "Fruit Cup Lid", "Plastic lid for fruit cup", "Non-Biodegradable", {"circular", "white", 0.12, "smooth", "Generic", 10, false, false, false} },
  { 114, "Bento Box", "Reusable bento box", "Recyclable", {"rectangular", "transparent", 0.15, "smooth", "EcoPack", 13, false, false, false} },
  { 115, "Plastic Straw 3", "Yet another paper straw", "Biodegradable", {"cylindrical", "white", 0.15, "smooth", "None", 8, true, false, false} },
  { 116, "Disposable Gloves", "Disposable plastic gloves", "Non-Biodegradable", {"irregular", "white", 0.38, "smooth", "None", 27, false, false, false} },
  { 117, "Plastic Wrapper", "Generic plastic wrapper", "Non-Biodegradable", {"irregular", "multicolor", 0.40, "patterned", "None", 30, true, false, false} },
  { 118, "Paper Wrapper", "Generic paper wrapper", "Biodegradable", {"irregular", "white", 0.42, "rough", "None", 32, true, false, false} },
  { 119, "Cup Sleeve", "Paper sleeve for cups", "Biodegradable", {"cylindrical", "brown", 0.20, "rough", "CoffeeCo", 14, true, false, false} },
  { 120, "Fruit Pouch", "Plastic pouch for fruit juice", "Recyclable", {"irregular", "orange", 0.18, "smooth", "Juicy", 11, false, false, false} },
  { 121, "Veggie Pouch", "Plastic pouch for vegetable puree", "Recyclable", {"irregular", "green", 0.20, "smooth", "FreshPack", 12, false, false, false} },
  { 122, "Snack Pouch", "Plastic pouch for snacks", "Non-Biodegradable", {"irregular", "multicolor", 0.35, "patterned", "SnackCo", 28, true, false, false} },
  { 123, "Ice Pack", "Reusable ice pack", "Non-Biodegradable", {"irregular", "white", 0.15, "smooth", "CoolPack", 10, false, false, false} },
  { 124, "Plastic Container Lid", "Plastic lid for container", "Non-Biodegradable", {"circular", "white", 0.10, "smooth", "Generic", 9, false, false, false} },
  { 125, "Paper Container Lid", "Paper lid for container", "Biodegradable", {"circular", "white", 0.12, "rough", "EcoPack", 11, true, false, false} },
  { 126, "Disposable Fork 2", "Another disposable fork", "Non-Biodegradable", {"irregular", "white", 0.30, "patterned", "None", 25, false, false, true} },
  { 127, "Disposable Knife 2", "Another disposable knife", "Non-Biodegradable", {"irregular", "white", 0.28, "patterned", "None", 24, false, false, true} },
  { 128, "Disposable Spoon 3", "Yet another disposable spoon", "Non-Biodegradable", {"irregular", "white", 0.35, "smooth", "None", 26, false, false, true} },
  { 129, "Eco-friendly Straw", "Straw made from biodegradable materials", "Biodegradable", {"cylindrical", "white", 0.14, "smooth", "EcoPack", 8, true, false, false} },
  { 130, "Reusable Utensils", "Set of reusable utensils", "Recyclable", {"irregular", "white", 0.10, "smooth", "EcoPack", 10, false, false, false} },
  { 131, "Paper Napkin 4", "Yet another paper napkin", "Biodegradable", {"irregular", "white", 0.42, "rough", "None", 34, true, false, false} },
  { 132, "Plastic Cup 3", "Another variant of plastic cup", "Non-Biodegradable", {"conical", "blue", 0.16, "smooth", "Generic", 14, false, false, false} },
  { 133, "Recyclable Plastic Bottle", "Plastic bottle designed for recycling", "Recyclable", {"cylindrical", "clear", 0.12, "smooth", "Coke", 10, false, false, false} },
  { 134, "Aluminum Bottle", "Bottle made from aluminum", "Recyclable", {"cylindrical", "silver", 0.09, "smooth", "FoodCo", 12, false, true, false} },
  { 135, "Eco-friendly Packaging", "Packaging made from sustainable materials", "Biodegradable", {"rectangular", "brown", 0.30, "rough", "EcoPack", 22, true, false, false} },
  { 136, "Plastic Straw 4", "Another variant of plastic straw", "Non-Biodegradable", {"cylindrical", "transparent", 0.05, "smooth", "None", 5, false, false, false} },
  { 137, "Biodegradable Plastic Bag", "Plastic bag made to biodegrade", "Biodegradable", {"irregular", "transparent", 0.20, "smooth", "EcoPack", 17, true, false, false} },
  { 138, "Non-Biodegradable Plastic Bag", "Standard plastic bag", "Non-Biodegradable", {"irregular", "transparent", 0.20, "smooth", "None", 17, false, false, false} },
  { 139, "Paper Bag 3", "Another paper bag", "Biodegradable", {"rectangular", "brown", 0.30, "rough", "EcoPack", 22, true, false, false} },
  { 140, "Cardboard Sleeve", "Cardboard sleeve for takeout", "Biodegradable", {"rectangular", "brown", 0.35, "rough", "None", 27, true, false, false} },
  { 141, "Foam Tray", "Disposable foam food tray", "Non-Biodegradable", {"rectangular", "white", 0.12, "smooth", "FoamCo", 14, false, false, true} },
  { 142, "Recyclable Foam Tray", "Foam tray designed for recycling", "Recyclable", {"rectangular", "white", 0.10, "smooth", "FoamCo", 13, false, false, true} },
  { 143, "Metallic Straw", "Straw with metallic finish", "Non-Biodegradable", {"cylindrical", "silver", 0.07, "smooth", "None", 6, false, true, false} },
  { 144, "Biodegradable Cup", "Cup made from biodegradable material", "Biodegradable", {"conical", "white", 0.22, "rough", "EcoPack", 16, true, false, false} },
  { 145, "Recyclable Cup", "Cup made for recycling", "Recyclable", {"conical", "white", 0.18, "smooth", "EcoPack", 14, false, false, false} },
  { 146, "Non-Biodegradable Cup", "Standard disposable cup", "Non-Biodegradable", {"conical", "blue", 0.15, "smooth", "Generic", 12, false, false, false} },
  { 147, "Eco-friendly Plate", "Plate made from eco-friendly material", "Biodegradable", {"circular", "white", 0.22, "rough", "EcoPack", 17, true, false, false} },
  { 148, "Recyclable Plate", "Plate designed for recycling", "Recyclable", {"circular", "white", 0.18, "smooth", "EcoPack", 16, false, false, false} },
  { 149, "Non-Biodegradable Plate", "Standard disposable plate", "Non-Biodegradable", {"circular", "white", 0.22, "smooth", "Generic", 19, false, false, false} },
  { 150, "Biodegradable Utensil", "Utensil made from biodegradable material", "Biodegradable", {"irregular", "white", 0.30, "patterned", "EcoPack", 24, false, false, true} },
  { 151, "Recyclable Utensil", "Utensil designed for recycling", "Recyclable", {"irregular", "white", 0.28, "patterned", "EcoPack", 23, false, false, true} },
  { 152, "Non-Biodegradable Utensil", "Standard disposable utensil", "Non-Biodegradable", {"irregular", "white", 0.35, "patterned", "Generic", 26, false, false, true} },
  { 153, "Biodegradable Bowl", "Bowl made from biodegradable material", "Biodegradable", {"circular", "white", 0.20, "rough", "EcoPack", 17, true, false, false} },
  { 154, "Recyclable Bowl", "Bowl designed for recycling", "Recyclable", {"circular", "white", 0.18, "smooth", "EcoPack", 16, false, false, false} },
  { 155, "Non-Biodegradable Bowl", "Standard disposable bowl", "Non-Biodegradable", {"circular", "white", 0.22, "smooth", "Generic", 19, false, false, false} },
  { 156, "Biodegradable Container", "Container made from biodegradable material", "Biodegradable", {"rectangular", "brown", 0.25, "rough", "EcoPack", 20, true, false, false} },
  { 157, "Recyclable Container", "Container designed for recycling", "Recyclable", {"rectangular", "transparent", 0.17, "smooth", "FreshPack", 14, false, false, false} },
  { 158, "Non-Biodegradable Container", "Standard disposable container", "Non-Biodegradable", {"rectangular", "white", 0.20, "smooth", "Generic", 18, false, false, false} },
  { 159, "Biodegradable Cutlery", "Cutlery made from biodegradable materials", "Biodegradable", {"irregular", "white", 0.30, "patterned", "EcoPack", 24, false, false, true} },
  { 160, "Recyclable Cutlery", "Cutlery designed for recycling", "Recyclable", {"irregular", "white", 0.28, "patterned", "EcoPack", 23, false, false, true} },
  { 161, "Non-Biodegradable Cutlery", "Standard disposable cutlery", "Non-Biodegradable", {"irregular", "white", 0.35, "patterned", "Generic", 26, false, false, true} },
  { 162, "Biodegradable Snack Box", "Snack box made from biodegradable material", "Biodegradable", {"rectangular", "brown", 0.30, "rough", "EcoPack", 21, true, false, false} },
  { 163, "Recyclable Snack Box", "Snack box designed for recycling", "Recyclable", {"rectangular", "brown", 0.25, "smooth", "EcoPack", 20, false, false, false} },
  { 164, "Non-Biodegradable Snack Box", "Standard disposable snack box", "Non-Biodegradable", {"rectangular", "brown", 0.32, "rough", "Generic", 22, false, false, false} },
  { 165, "Biodegradable Food Tray", "Food tray made from biodegradable material", "Biodegradable", {"rectangular", "white", 0.24, "rough", "EcoPack", 18, true, false, true} },
  { 166, "Recyclable Food Tray", "Food tray designed for recycling", "Recyclable", {"rectangular", "white", 0.20, "smooth", "EcoPack", 16, false, false, true} },
  { 167, "Non-Biodegradable Food Tray", "Standard disposable food tray", "Non-Biodegradable", {"rectangular", "white", 0.26, "smooth", "Generic", 19, false, false, true} },
  { 168, "Biodegradable Beverage Can", "Beverage can made from biodegradable material", "Biodegradable", {"cylindrical", "silver", 0.10, "smooth", "EcoPack", 15, false, true, false} },
  { 169, "Recyclable Beverage Can", "Beverage can designed for recycling", "Recyclable", {"cylindrical", "silver", 0.10, "smooth", "EcoPack", 15, false, true, false} }
};

const int wasteTemplatesCount = sizeof(wasteTemplates) / sizeof(WasteTemplate);

#endif
